// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace KaminiCenter.Data.Migrations
{
    public partial class EditAccessorieProporties : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Name",
                table: "Accessories");

            migrationBuilder.AddColumn<string>(
                name: "GroupId",
                table: "Accessories",
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "IX_Accessories_GroupId",
                table: "Accessories",
                column: "GroupId");

            migrationBuilder.AddForeignKey(
                name: "FK_Accessories_Product_Groups_GroupId",
                table: "Accessories",
                column: "GroupId",
                principalTable: "Product_Groups",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Accessories_Product_Groups_GroupId",
                table: "Accessories");

            migrationBuilder.DropIndex(
                name: "IX_Accessories_GroupId",
                table: "Accessories");

            migrationBuilder.DropColumn(
                name: "GroupId",
                table: "Accessories");

            migrationBuilder.AddColumn<string>(
                name: "Name",
                table: "Accessories",
                type: "nvarchar(max)",
                nullable: true);
        }
    }
}
